#!/usr/bin/env node
/**
 * Flatten tokens/*.json into dist/tokens.css as CSS custom properties.
 *
 * Zero dependencies. Convention (see tokens/README.md):
 *   tokens/scale.json        theme-independent scales  -> :root
 *   tokens/theme.dark.json   semantic colours (dark)   -> :root + [data-theme="dark"]
 *   tokens/theme.light.json  semantic colours (light)  -> [data-theme="light"]
 *
 * Nested JSON keys become dash-joined token names:
 *   color.severity.critical.bg -> --zq-color-severity-critical-bg
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PREFIX = "zq";

const read = (name) => JSON.parse(readFileSync(join(ROOT, "tokens", name), "utf8"));

/** Flatten nested objects to [{ name, value }], skipping `$`-prefixed metadata. */
function flatten(node, path = []) {
  const out = [];
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    const next = [...path, key];
    if (value !== null && typeof value === "object") out.push(...flatten(value, next));
    else out.push({ name: `--${PREFIX}-${next.join("-")}`, value: String(value) });
  }
  return out;
}

function block(selector, tokens, note) {
  const body = tokens.map((t) => `  ${t.name}: ${t.value};`).join("\n");
  return `${note ? `/* ${note} */\n` : ""}${selector} {\n${body}\n}\n`;
}

const scale = flatten(read("scale.json"));
const dark = flatten(read("theme.dark.json"));
const light = flatten(read("theme.light.json"));

const header =
  "/* zeroquarry-ui — generated by scripts/build-tokens.mjs. DO NOT EDIT.\n" +
  "   Edit tokens/*.json and run `npm run build`. */\n\n";

const css =
  header +
  block(":root", scale, "scales (theme-independent)") +
  "\n" +
  block(":root,\n[data-theme=\"dark\"]", dark, "semantic colour — dark (default)") +
  "\n" +
  block("[data-theme=\"light\"]", light, "semantic colour — light") +
  "\n" +
  "/* Opt-in: follow the OS when the app sets data-theme=\"auto\". */\n" +
  "@media (prefers-color-scheme: light) {\n" +
  "  [data-theme=\"auto\"] {\n" +
  light.map((t) => `    ${t.name}: ${t.value};`).join("\n") +
  "\n  }\n}\n";

mkdirSync(join(ROOT, "dist"), { recursive: true });
writeFileSync(join(ROOT, "dist", "tokens.css"), css);

console.log(
  `tokens.css written — ${scale.length} scale + ${dark.length} dark + ${light.length} light tokens ` +
  `(${scale.length + dark.length + light.length} custom properties)`
);
